### ISSUE TITLE
 How should I use the GUI interface ?

### ISSUE THREAD

**Issue by Harry710887048** [zhaofuq/Instant-NSR#10]
Some error occured when running nerf_gui.py，how to solve this problem?
 
![07fd2dda59f9abe2c94e3574f809dea](https://user-images.githubusercontent.com/75151571/206102500-1d7dda7c-86e2-4ac5-a6f5-021e177dd734.png)
![c3eadecc32773c134fea9a5353761c7](https://user-images.githubusercontent.com/75151571/206102597-4680eb35-43b2-45b3-84c8-1054e8bb82d8.png)

**Comment by zhaofuq** [comment]
Sorry, GUI is not supported now.
