### ISSUE TITLE
How to run in dynamic video ?

### ISSUE THREAD

**Issue by Harry710887048** [zhaofuq/Instant-NSR#11]
It seems to be a dynamic NeRF in your paper. Can the code implement this function ?

**Comment by zhaofuq** [comment]
Our dynamic NeRF results are reconstructed frame-by-frame as claimed in our paper, which means you can run it for every frame.

**Comment by xiliu8006** [comment]
How do we design the deformation refinement network? Is the pipeline differentiable?
