### ISSUE TITLE
Usage of TSDF

### ISSUE THREAD

**Issue by Triansh** [zhaofuq/Instant-NSR#12]
Hello. Please point out in which file you have implemented TSDF-based volumetric rendering.
Thank You

**Comment by zhaofuq** [comment]
We implemented TSDF-based volumetric rendering in our CUDA implementation, not in this pytorch version.

**Comment by Triansh** [comment]
Have you released a public version of your CUDA implementation?
Would like to enquire the same about the neural tracking part mentioned in the research paper.

**Comment by xyp8023** [comment]
Hi,

If this pytorch version does not have the TSDF-based volumetric rendering, I am wondering how come there isn't the numerical stability issue? I did manage to get good results with the default `network_sdf` on the dance dataset you provided.
