### ISSUE TITLE
Some error in training.

### ISSUE THREAD

**Issue by Harry710887048** [zhaofuq/Instant-NSR#8]
![00f11b2b23f0f7f72b0dc3e5071402c](https://user-images.githubusercontent.com/75151571/204294318-4372be82-68b6-4b57-91d5-f3f1f4c00243.png)
![8d6044769283c16c8151f880bf3b5e1](https://user-images.githubusercontent.com/75151571/204294346-8b2a4711-6e82-4588-8971-e2296732ea56.png)
How did this bmm failure error generate ?How should I solve this problem ?
作者您好！我再运行nerf.py文件时遇到了一些问题，torch.bmm这一步的时候遇到了问题，这是否是cuda版本的问题？我该如何解决呢？

**Comment by gaojunjie1999** [comment]
Hi 你好呀 请问这个问题你怎么解决的呢
